import * as TextDocuments from '../TextDocuments/TextDocuments.ts'

export const commandMap = {
  'TextDocument.applyEdits': TextDocuments.applyEdits,
  'TextDocument.cursorDocumentEnd': TextDocuments.cursorDocumentEnd,
  'TextDocument.cursorDocumentStart': TextDocuments.cursorDocumentStart,
  'TextDocument.cursorDown': TextDocuments.cursorDown,
  'TextDocument.cursorEnd': TextDocuments.cursorEnd,
  'TextDocument.cursorHome': TextDocuments.cursorHome,
  'TextDocument.cursorLeft': TextDocuments.cursorLeft,
  'TextDocument.cursorRight': TextDocuments.cursorRight,
  'TextDocument.cursorUp': TextDocuments.cursorUp,
  'TextDocument.cursorWordLeft': TextDocuments.cursorWordLeft,
  'TextDocument.cursorWordRight': TextDocuments.cursorWordRight,
  'TextDocument.deleteAllLeft': TextDocuments.deleteAllLeft,
  'TextDocument.deleteAllRight': TextDocuments.deleteAllRight,
  'TextDocument.deleteCharacterLeft': TextDocuments.deleteCharacterLeft,
  'TextDocument.deleteCharacterRight': TextDocuments.deleteCharacterRight,
  'TextDocument.deleteWordLeft': TextDocuments.deleteWordLeft,
  'TextDocument.deleteWordRight': TextDocuments.deleteWordRight,
  'TextDocument.dispose': TextDocuments.dispose,
  'TextDocument.getLines': TextDocuments.getLines,
  'TextDocument.getSelectedText': TextDocuments.getSelectedText,
  'TextDocument.getSnapshot': TextDocuments.getSnapshot,
  'TextDocument.getText': TextDocuments.getText,
  'TextDocument.insertLineBreak': TextDocuments.insertLineBreak,
  'TextDocument.insertTab': TextDocuments.insertTab,
  'TextDocument.markSaved': TextDocuments.markSaved,
  'TextDocument.pasteText': TextDocuments.pasteText,
  'TextDocument.redo': TextDocuments.redo,
  'TextDocument.selectAll': TextDocuments.selectAll,
  'TextDocument.selectDown': TextDocuments.selectDown,
  'TextDocument.selectEnd': TextDocuments.selectEnd,
  'TextDocument.selectHome': TextDocuments.selectHome,
  'TextDocument.selectLeft': TextDocuments.selectLeft,
  'TextDocument.selectRight': TextDocuments.selectRight,
  'TextDocument.selectUp': TextDocuments.selectUp,
  'TextDocument.selectWordLeft': TextDocuments.selectWordLeft,
  'TextDocument.selectWordRight': TextDocuments.selectWordRight,
  'TextDocument.setContent': TextDocuments.setContent,
  'TextDocument.setSelections': TextDocuments.setSelections,
  'TextDocument.type': TextDocuments.type,
  'TextDocument.undo': TextDocuments.undo,
}
