import { expect, test } from '@jest/globals'
import { commandMap } from '../src/parts/CommandMap/CommandMap.ts'

test('contains editor integration commands', () => {
  expect(Object.keys(commandMap)).toEqual(
    expect.arrayContaining([
      'Editor.closeFind',
      'Editor.create',
      'Editor.create2',
      'Editor.copy',
      'Editor.cursorDocumentEnd',
      'Editor.cursorDocumentStart',
      'Editor.cursorDown',
      'Editor.cursorEnd',
      'Editor.cursorHome',
      'Editor.cursorLeft',
      'Editor.cursorRight',
      'Editor.cursorUp',
      'Editor.cursorWordLeft',
      'Editor.cursorWordRight',
      'Editor.cut',
      'Editor.deleteAllLeft',
      'Editor.deleteAllRight',
      'Editor.deleteCharacterLeft',
      'Editor.deleteCharacterRight',
      'Editor.deleteLine',
      'Editor.deleteWordLeft',
      'Editor.deleteWordRight',
      'Editor.diff2',
      'Editor.dispose',
      'Editor.getCommandIds',
      'Editor.getKeyBindings',
      'Editor.getSelections2',
      'Editor.getText',
      'Editor.getQuickPickMenuEntries',
      'Editor.handleClick',
      'Editor.handleBeforeInput',
      'Editor.handleInput',
      'Editor.handleWheel',
      'Editor.indent',
      'Editor.insertLineBreak',
      'Editor.insertTab',
      'Editor.loadContent',
      'Editor.openFind',
      'Editor.openFind2',
      'Editor.paste',
      'Editor.pasteText',
      'Editor.pointerDown',
      'Editor.pointerMove',
      'Editor.pointerUp',
      'Editor.redo',
      'Editor.render2',
      'Editor.renderEventListeners',
      'Editor.resize',
      'Editor.save',
      'Editor.selectAll',
      'Editor.selectDown',
      'Editor.selectDocumentEnd',
      'Editor.selectDocumentStart',
      'Editor.selectEnd',
      'Editor.selectHome',
      'Editor.selectLeft',
      'Editor.selectRight',
      'Editor.selectUp',
      'Editor.selectWordLeft',
      'Editor.selectWordRight',
      'Editor.setDiagnostics',
      'Editor.setSelections2',
      'Editor.type',
      'Editor.undo',
      'Editor.unindent',
      'Editor.updateDiagnostics',
      'FindWidget.close',
      'Font.ensure',
      'Initialize.initialize',
      'TextDocumentWorker.setPort',
    ]),
  )
  expect(commandMap['Editor.getCommandIds']()).toEqual(
    expect.arrayContaining([
      'cursorCharacterLeft',
      'deleteCharacterLeft',
      'getText',
      'handleBeforeInput',
      'paste',
      'save',
      'setSelections2',
      'type',
      'undo',
    ]),
  )
  expect(commandMap['Editor.getKeyBindings']()).toHaveLength(24)
  expect(commandMap['Editor.getQuickPickMenuEntries']()).toEqual([])
  expect(commandMap['Editor.handleClick']).toEqual(expect.any(Function))
  expect(commandMap['Editor.handleInput']).toEqual(expect.any(Function))
  expect(commandMap['Editor.loadContent']).toEqual(expect.any(Function))
  expect(commandMap['Editor.openFind']).toEqual(expect.any(Function))
  expect(commandMap['Editor.openFind2']).toEqual(expect.any(Function))
  expect(commandMap['Editor.renderEventListeners']()).toHaveLength(7)
  expect(commandMap['Editor.setDiagnostics']).toEqual(expect.any(Function))
  expect(commandMap['Editor.setSelections2']).toEqual(expect.any(Function))
  expect(commandMap['Editor.updateDiagnostics']()).toBeUndefined()
  expect(commandMap['Font.ensure']()).toBeUndefined()
  expect(commandMap['FindWidget.close']).toEqual(expect.any(Function))
  expect(commandMap['Initialize.initialize']()).toBeUndefined()
  expect(commandMap['TextDocumentWorker.setPort']).toEqual(expect.any(Function))
})
